interface ICameraEditor{
    "isViewingGallery": boolean,
    "isViewingEditor":boolean,
    "selectedCameraIndex": number,
    "isViewingCelsius": boolean,
    "showHotspotNumbers": boolean,
    "isEditing": boolean,
    "isViewingAIVisionViewer": boolean,
    "isWatchingLive":boolean,
    "isRetaining":boolean,
    "minZoomLevel":number,
    "maxZoomLevel":number,
    "defaultZoomLevel":number,
    "cameras": ICamera[],
    "tags": ITag[],
};