interface ICamera{
    name:string|null,
    existingName:string|null,
    isOnline:boolean,
    isThermalCamera: boolean,
    canRenameCamera: boolean,
    canEditRotation: boolean,
    canEdit: boolean,
    canDeleteCamera: boolean,
    api: string|null,
    url:string|null,
    usbIndex: number|null,
    canEditMirror: boolean,
    isKnown: boolean,
    canEditMaterialLayer: boolean,
    canEditDistanceLayer: boolean,
    canAddPolygonSpot: boolean,
    canMoveSpots: boolean,
    canAddPointSpot: boolean,
    canDeleteSpots: boolean,
    canRenameSpots: boolean,
    canChangeSpotColor: boolean,
    materialMap: any|null,
    distanceMap: any|null,
    imageConfidence: number
    nativeWidth: number,
    nativeHeight: number,
    rotation: number,
    imageMirrorHorizontally: boolean,
    timeStamp: string|null

}